include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false 
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart" 
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.gr.dart"
  errors:
    missing_required_param: error
    missing_return: error
    unused_import: warning
    dead_code: warning
    unnecessary_cast: warning
    always_declare_return_types: error
    depend_on_referenced_packages: ignore
    invalid_use_of_protected_member: ignore
    constant_identifier_names: ignore
    use_build_context_synchronously: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_dynamic_calls: ignore
    prefer_single_quotes: ignore

linter:
  rules:
    # 🚀 **SOLID Principles & Code Maintainability**
    - avoid_classes_with_only_static_members 
    - prefer_mixin
    - avoid_setters_without_getters 
    - prefer_final_in_for_each
    - prefer_expression_function_bodies 

    # 🎯 **Clean Code & Readability**
    - prefer_const_constructors 
    - prefer_const_declarations
    - avoid_redundant_argument_values
    - avoid_positional_boolean_parameters 
    - always_declare_return_types 
    - prefer_typing_uninitialized_variables

    # 🔥 **Performance & Optimization**
    - avoid_unnecessary_containers
    - use_super_parameters 
    - use_setters_to_change_properties

    # 🎨 **Consistency & Best Practices**
    - prefer_single_quotes
    - avoid_relative_lib_imports 
    - prefer_relative_imports 
    - require_trailing_commas

    # 🛑 **Avoid Common Mistakes**
    - avoid_print 
    - avoid_dynamic_calls 
    - avoid_types_as_parameter_names 
    - cancel_subscriptions
    - close_sinks 
