name: fcm_eraser_plus
description: "The plugin has been upgraded and extended with additional features for working with FCM"
version: 1.1.2
homepage: https://github.com/AnhPhon/fcm_eraser_plus

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: any

  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: eraser.fcm.plus.fcm_eraser_plus
        pluginClass: FcmEraserPlusPlugin
      ios:
        pluginClass: FcmEraserPlusPlugin